.TH MOCCAMASTER "1" "November 2017" "Webstep (www.webstep.no)" "Trondheim"
.SH NAME
moccamaster \- transforms H2O and coffee beans into a productivity enhancing substance

.SH DESCRIPTION
.B moccamaster
requires fresh and pure H2O and 78g of freshly grinded coffee beans (or just "filterkaffe") from your favorite retail store. The device will use heat elements to drain the H2O (water) from the tank and pour a small continuous stream of water into the brewer where the grinded coffee is. The brewer will produce a steady stream of fresh coffee into the coffee pot. A full batch will easily produce around 10 cups of coffee.

.PP
.nr step 1 1
Step by step:
.IP \n[step]. 3
Fold the filter paper so it sits nicely in the basket
.IP \n+[step].
Rinse the paper and basket with hot water (removes the taste of paper and warms the basket)
.IP \n+[step].
Grind 78g of coffee
.IP \n+[step].
Fill tank with fresh cold water
.IP \n+[step].
Set the filter basket to closed (marked X)
.IP \n+[step].
Start the brewer
.IP \n+[step].
Stir! Once the filter basket is half\-full of water, use a spoon to mix the slurry and make sure the grounds are all evenly damped \- be careful not to rip the filter paper
.IP \n+[step].
Set the basket to open \- you don't want it to overflow! (marked O)
.IP \n+[step].
Towards the end of the brew, gently lift, tap and re\-seat the filter basket in its holder. This will help settle the bed of grounds to ensure an even extraction
.IP \n+[step].
Spread the news. A fresh can of coffee is a key ingrediens to a innovative and creative working environment

.SH IMPORTANT
If you empty the coffee pot (take the last cup?) you are obligated to create a new batch - "goto step 1"

.SH BUGS
A common error is to forget to set the filter basket to open (marked O) - thus overflowing the basket and creating a mess.. Don't be that person!
Another common error is to use too much coffee. If you don't have a proper weight scale, then usually 4-5 spoons (not topped) is sufficient.

.SH AUTHORS
Written by Asbjørn A. Fellinghaug <asbjorn@fellinghaug.com>

.SH "REPORTING BUGS"
Open a Github issue! I'm also always open to review a pull request.

.SH SEE ALSO
.PP
Here are some more reading material which describes the process into further details:
.IP \(bu 2
\fB\fChttps://samplecoffee.com.au/brewguides/moccamaster\fR
.IP \(bu 2
\fB\fChttps://grumpytechie.net/2013/12/13/how-to-properly-use-your-technivorm-moccamaster-or-any-drip-brewer-for-that-matter\fR
